birds = [
{value:"1139", label:"Acadian Flycatcher"},
{value:"1140", label:"Alder Flycatcher"},
{value:"392", label:"American Avocet"},
{value:"218", label:"American Bittern"},
{value:"36", label:"American Black Duck"},
{value:"360", label:"American Coot"},
{value:"1296", label:"American Crow"},
{value:"373", label:"American Golden-Plover"},
{value:"1868", label:"American Goldfinch"},
{value:"323", label:"American Kestrel"},
{value:"388", label:"American Oystercatcher"},
{value:"1521", label:"American Pipit"},
{value:"1576", label:"American Redstart"},
{value:"1472", label:"American Robin"},
{value:"1704", label:"American Tree Sparrow"},
{value:"205", label:"American White Pelican"},
{value:"35", label:"American Wigeon"},
{value:"456", label:"American Woodcock"},
{value:"213", label:"Anhinga"},
{value:"710", label:"Antillean Nighthawk"},
{value:"502", label:"Arctic Tern"},
{value:"1167", label:"Ash-throated Flycatcher"},
{value:"532", label:"Atlantic Puffin"},
{value:"180", label:"Audubon's Shearwater"},
{value:"1697", label:"Bachman's Sparrow"},
{value:"437", label:"Baird's Sandpiper"},
{value:"270", label:"Bald Eagle"},
{value:"1817", label:"Baltimore Oriole"},
{value:"188", label:"Band-rumped Storm-Petrel"},
{value:"1328", label:"Bank Swallow"},
{value:"664", label:"Barn Owl"},
{value:"1331", label:"Barn Swallow"},
{value:"20", label:"Barnacle Goose"},
{value:"696", label:"Barred Owl"},
{value:"421", label:"Bar-tailed Godwit"},
{value:"1568", label:"Bay-breasted Warbler"},
{value:"912", label:"Belted Kingfisher"},
{value:"154", label:"Bermuda Petrel"},
{value:"1382", label:"Bewick's Wren"},
{value:"338", label:"Black Rail"},
{value:"65", label:"Black Scoter"},
{value:"1937", label:"Black Skimmer"},
{value:"497", label:"Black Tern"},
{value:"255", label:"Black Vulture"},
{value:"1575", label:"Black-and-white Warbler"},
{value:"371", label:"Black-bellied Plover"},
{value:"183", label:"Black-bellied Storm-Petrel"},
{value:"648", label:"Black-billed Cuckoo"},
{value:"1556", label:"Blackburnian Warbler"},
{value:"1334", label:"Black-capped Chickadee"},
{value:"1981", label:"Black-capped Petrel"},
{value:"242", label:"Black-crowned Night-Heron"},
{value:"1994", label:"Black-headed Gull"},
{value:"1925", label:"Black-legged Kittiwake"},
{value:"391", label:"Black-necked Stilt"},
{value:"1569", label:"Blackpoll Warbler"},
{value:"419", label:"Black-tailed Godwit"},
{value:"463", label:"Black-tailed Gull"},
{value:"1549", label:"Black-throated Blue Warbler"},
{value:"1553", label:"Black-throated Green Warbler"},
{value:"1259", label:"Black-whiskered Vireo"},
{value:"1763", label:"Blue Grosbeak"},
{value:"1270", label:"Blue Jay"},
{value:"2010", label:"Blue-gray Gnatcatcher"},
{value:"1250", label:"Blue-headed Vireo"},
{value:"42", label:"Blue-winged Teal"},
{value:"1533", label:"Blue-winged Warbler"},
{value:"1787", label:"Boat-tailed Grackle"},
{value:"1771", label:"Bobolink"},
{value:"1993", label:"Bonaparte's Gull"},
{value:"19", label:"Brant"},
{value:"1785", label:"Brewer's Blackbird"},
{value:"488", label:"Bridled Tern"},
{value:"298", label:"Broad-winged Hawk"},
{value:"202", label:"Brown Booby"},
{value:"1351", label:"Brown Creeper"},
{value:"482", label:"Brown Noddy"},
{value:"206", label:"Brown Pelican"},
{value:"1492", label:"Brown Thrasher"},
{value:"1795", label:"Brown-headed Cowbird"},
{value:"1350", label:"Brown-headed Nuthatch"},
{value:"447", label:"Buff-breasted Sandpiper"},
{value:"67", label:"Bufflehead"},
{value:"163", label:"Bulwer's Petrel"},
{value:"21", label:"Cackling Goose"},
{value:"466", label:"California Gull"},
{value:"22", label:"Canada Goose"},
{value:"1602", label:"Canada Warbler"},
{value:"50", label:"Canvasback"},
{value:"1548", label:"Cape May Warbler"},
{value:"168", label:"Cape Verde Shearwater"},
{value:"1333", label:"Carolina Chickadee"},
{value:"1378", label:"Carolina Wren"},
{value:"495", label:"Caspian Tern"},
{value:"236", label:"Cattle Egret"},
{value:"1330", label:"Cave Swallow"},
{value:"1525", label:"Cedar Waxwing"},
{value:"1570", label:"Cerulean Warbler"},
{value:"1546", label:"Chestnut-sided Warbler"},
{value:"741", label:"Chimney Swift"},
{value:"1705", label:"Chipping Sparrow"},
{value:"718", label:"Chuck-will's-widow"},
{value:"43", label:"Cinnamon Teal"},
{value:"340", label:"Clapper Rail"},
{value:"141", label:"Clark's Grebe"},
{value:"2048", label:"Clay-colored Sparrow"},
{value:"1329", label:"Cliff Swallow"},
{value:"60", label:"Common Eider"},
{value:"357", label:"Common Gallinule"},
{value:"68", label:"Common Goldeneye"},
{value:"1786", label:"Common Grackle"},
{value:"560", label:"Common Ground-Dove"},
{value:"136", label:"Common Loon"},
{value:"72", label:"Common Merganser"},
{value:"514", label:"Common Murre"},
{value:"709", label:"Common Nighthawk"},
{value:"1307", label:"Common Raven"},
{value:"1857", label:"Common Redpoll"},
{value:"501", label:"Common Tern"},
{value:"1587", label:"Common Yellowthroat"},
{value:"1584", label:"Connecticut Warbler"},
{value:"279", label:"Cooper's Hawk"},
{value:"167", label:"Cory's Shearwater"},
{value:"443", label:"Curlew Sandpiper"},
{value:"1730", label:"Dark-eyed Junco"},
{value:"1770", label:"Dickcissel"},
{value:"209", label:"Double-crested Cormorant"},
{value:"513", label:"Dovekie"},
{value:"963", label:"Downy Woodpecker"},
{value:"442", label:"Dunlin"},
{value:"1985", label:"Eared Grebe"},
{value:"1428", label:"Eastern Bluebird"},
{value:"1196", label:"Eastern Kingbird"},
{value:"1779", label:"Eastern Meadowlark"},
{value:"1154", label:"Eastern Phoebe"},
{value:"669", label:"Eastern Screech-Owl"},
{value:"1689", label:"Eastern Towhee"},
{value:"724", label:"Eastern Whip-poor-will"},
{value:"1132", label:"Eastern Wood-Pewee"},
{value:"550", label:"Eurasian Collared-Dove"},
{value:"34", label:"Eurasian Wigeon"},
{value:"1509", label:"European Starling"},
{value:"182", label:"European Storm-Petrel"},
{value:"1875", label:"Evening Grosbeak"},
{value:"0", label:"Fea's Petrel"},
{value:"1707", label:"Field Sparrow"},
{value:"1304", label:"Fish Crow"},
{value:"1201", label:"Fork-tailed Flycatcher"},
{value:"503", label:"Forster's Tern"},
{value:"1721", label:"Fox Sparrow"},
{value:"479", label:"Franklin's Gull"},
{value:"32", label:"Gadwall"},
{value:"47", label:"Garganey"},
{value:"476", label:"Glaucous Gull"},
{value:"247", label:"Glossy Ibis"},
{value:"310", label:"Golden Eagle"},
{value:"1402", label:"Golden-crowned Kinglet"},
{value:"1534", label:"Golden-winged Warbler"},
{value:"1716", label:"Grasshopper Sparrow"},
{value:"1485", label:"Gray Catbird"},
{value:"1197", label:"Gray Kingbird"},
{value:"1451", label:"Gray-cheeked Thrush"},
{value:"477", label:"Great Black-backed Gull"},
{value:"224", label:"Great Blue Heron"},
{value:"210", label:"Great Cormorant"},
{value:"1169", label:"Great Crested Flycatcher"},
{value:"227", label:"Great Egret"},
{value:"681", label:"Great Horned Owl"},
{value:"171", label:"Great Shearwater"},
{value:"508", label:"Great Skua"},
{value:"55", label:"Greater Scaup"},
{value:"14", label:"Greater White-fronted Goose"},
{value:"403", label:"Greater Yellowlegs"},
{value:"238", label:"Green Heron"},
{value:"49", label:"Green-winged Teal"},
{value:"494", label:"Gull-billed Tern"},
{value:"964", label:"Hairy Woodpecker"},
{value:"61", label:"Harlequin Duck"},
{value:"1727", label:"Harris's Sparrow"},
{value:"1717", label:"Henslow's Sparrow"},
{value:"151", label:"Herald Petrel"},
{value:"1454", label:"Hermit Thrush"},
{value:"467", label:"Herring Gull"},
{value:"71", label:"Hooded Merganser"},
{value:"1600", label:"Hooded Warbler"},
{value:"1986", label:"Horned Grebe"},
{value:"1310", label:"Horned Lark"},
{value:"10371", label:"House Finch"},
{value:"1907", label:"House Sparrow"},
{value:"1384", label:"House Wren"},
{value:"420", label:"Hudsonian Godwit"},
{value:"470", label:"Iceland Gull"},
{value:"1765", label:"Indigo Bunting"},
{value:"1583", label:"Kentucky Warbler"},
{value:"384", label:"Killdeer"},
{value:"59", label:"King Eider"},
{value:"341", label:"King Rail"},
{value:"1733", label:"Lapland Longspur"},
{value:"1714", label:"Lark Bunting"},
{value:"1711", label:"Lark Sparrow"},
{value:"1990", label:"Laughing Gull"},
{value:"2040", label:"Le Conte's Sparrow"},
{value:"186", label:"Leach's Storm-Petrel"},
{value:"220", label:"Least Bittern"},
{value:"1143", label:"Least Flycatcher"},
{value:"435", label:"Least Sandpiper"},
{value:"491", label:"Least Tern"},
{value:"471", label:"Lesser Black-backed Gull"},
{value:"56", label:"Lesser Scaup"},
{value:"406", label:"Lesser Yellowlegs"},
{value:"364", label:"Limpkin"},
{value:"1723", label:"Lincoln's Sparrow"},
{value:"233", label:"Little Blue Heron"},
{value:"233", label:"Little Blue Heron"},
{value:"461", label:"Little Gull"},
{value:"432", label:"Little Stint"},
{value:"1230", label:"Loggerhead Shrike"},
{value:"418", label:"Long-billed Curlew"},
{value:"450", label:"Long-billed Dowitcher"},
{value:"699", label:"Long-eared Owl"},
{value:"66", label:"Long-tailed Duck"},
{value:"512", label:"Long-tailed Jaeger"},
{value:"1582", label:"Louisiana Waterthrush"},
{value:"1586", label:"MacGillivray's Warbler"},
{value:"214", label:"Magnificent Frigatebird"},
{value:"1547", label:"Magnolia Warbler"},
{value:"37", label:"Mallard"},
{value:"177", label:"Manx Shearwater"},
{value:"422", label:"Marbled Godwit"},
{value:"1391", label:"Marsh Wren"},
{value:"198", label:"Masked Booby"},
{value:"325", label:"Merlin"},
{value:"464", label:"Mew Gull"},
{value:"2038", label:"Mississippi Kite"},
{value:"556", label:"Mourning Dove"},
{value:"1585", label:"Mourning Warbler"},
{value:"24", label:"Mute Swan"},
{value:"1537", label:"Nashville Warbler"},
{value:"2041", label:"Nelson's Sparrow"},
{value:"122", label:"Northern Bobwhite"},
{value:"1755", label:"Northern Cardinal"},
{value:"979", label:"Northern Flicker"},
{value:"1983", label:"Northern Fulmar"},
{value:"204", label:"Northern Gannet"},
{value:"282", label:"Northern Goshawk"},
{value:"274", label:"Northern Harrier"},
{value:"369", label:"Northern Lapwing"},
{value:"1487", label:"Northern Mockingbird"},
{value:"1543", label:"Northern Parula"},
{value:"46", label:"Northern Pintail"},
{value:"1326", label:"Northern Rough-winged Swallow"},
{value:"705", label:"Northern Saw-whet Owl"},
{value:"44", label:"Northern Shoveler"},
{value:"1231", label:"Northern Shrike"},
{value:"1581", label:"Northern Waterthrush"},
{value:"1426", label:"Northern Wheatear"},
{value:"1127", label:"Olive-sided Flycatcher"},
{value:"1536", label:"Orange-crowned Warbler"},
{value:"1804", label:"Orchard Oriole"},
{value:"2005", label:"Osprey"},
{value:"1580", label:"Ovenbird"},
{value:"135", label:"Pacific Loon"},
{value:"1769", label:"Painted Bunting"},
{value:"1567", label:"Palm Warbler"},
{value:"511", label:"Parasitic Jaeger"},
{value:"438", label:"Pectoral Sandpiper"},
{value:"331", label:"Peregrine Falcon"},
{value:"1256", label:"Philadelphia Vireo"},
{value:"138", label:"Pied-billed Grebe"},
{value:"985", label:"Pileated Woodpecker"},
{value:"1860", label:"Pine Siskin"},
{value:"1563", label:"Pine Warbler"},
{value:"382", label:"Piping Plover"},
{value:"510", label:"Pomarine Jaeger"},
{value:"1565", label:"Prairie Warbler"},
{value:"1577", label:"Prothonotary Warbler"},
{value:"10351", label:"Purple Finch"},
{value:"9871", label:"Purple Gallinule"},
{value:"1311", label:"Purple Martin"},
{value:"440", label:"Purple Sandpiper"},
{value:"516", label:"Razorbill"},
{value:"1854", label:"Red Crossbill"},
{value:"427", label:"Red Knot"},
{value:"459", label:"Red Phalarope"},
{value:"953", label:"Red-bellied Woodpecker"},
{value:"196", label:"Red-billed Tropicbird"},
{value:"73", label:"Red-breasted Merganser"},
{value:"1347", label:"Red-breasted Nuthatch"},
{value:"967", label:"Red-cockaded Woodpecker"},
{value:"235", label:"Reddish Egret"},
{value:"1257", label:"Red-eyed Vireo"},
{value:"51", label:"Redhead"},
{value:"940", label:"Red-headed Woodpecker"},
{value:"1987", label:"Red-necked Grebe"},
{value:"458", label:"Red-necked Phalarope"},
{value:"296", label:"Red-shouldered Hawk"},
{value:"305", label:"Red-tailed Hawk"},
{value:"134", label:"Red-throated Loon"},
{value:"1772", label:"Red-winged Blackbird"},
{value:"465", label:"Ring-billed Gull"},
{value:"53", label:"Ring-necked Duck"},
{value:"536", label:"Rock Pigeon"},
{value:"251", label:"Roseate Spoonbill"},
{value:"500", label:"Roseate Tern"},
{value:"1759", label:"Rose-breasted Grosbeak"},
{value:"18", label:"Ross's Goose"},
{value:"307", label:"Rough-legged Hawk"},
{value:"504", label:"Royal Tern"},
{value:"1403", label:"Ruby-crowned Kinglet"},
{value:"864", label:"Ruby-throated Hummingbird"},
{value:"75", label:"Ruddy Duck"},
{value:"423", label:"Ruddy Turnstone"},
{value:"448", label:"Ruff"},
{value:"98", label:"Ruffed Grouse"},
{value:"1784", label:"Rusty Blackbird"},
{value:"1988", label:"Sabine's Gull"},
{value:"1491", label:"Sage Thrasher"},
{value:"1718", label:"Saltmarsh Sparrow"},
{value:"428", label:"Sanderling"},
{value:"365", label:"Sandhill Crane"},
{value:"506", label:"Sandwich Tern"},
{value:"1715", label:"Savannah Sparrow"},
{value:"1956", label:"Scarlet Tanager"},
{value:"1200", label:"Scissor-tailed Flycatcher"},
{value:"1719", label:"Seaside Sparrow"},
{value:"1390", label:"Sedge Wren"},
{value:"381", label:"Semipalmated Plover"},
{value:"429", label:"Semipalmated Sandpiper"},
{value:"278", label:"Sharp-shinned Hawk"},
{value:"1793", label:"Shiny Cowbird"},
{value:"449", label:"Short-billed Dowitcher"},
{value:"701", label:"Short-eared Owl"},
{value:"472", label:"Slaty-backed Gull"},
{value:"1744", label:"Snow Bunting"},
{value:"17", label:"Snow Goose"},
{value:"232", label:"Snowy Egret"},
{value:"682", label:"Snowy Owl"},
{value:"378", label:"Snowy Plover"},
{value:"399", label:"Solitary Sandpiper"},
{value:"1722", label:"Song Sparrow"},
{value:"174", label:"Sooty Shearwater"},
{value:"486", label:"Sooty Tern"},
{value:"348", label:"Sora"},
{value:"509", label:"South Polar Skua"},
{value:"402", label:"Spotted Redshank"},
{value:"397", label:"Spotted Sandpiper"},
{value:"1522", label:"Sprague's Pipit"},
{value:"444", label:"Stilt Sandpiper"},
{value:"1955", label:"Summer Tanager"},
{value:"63", label:"Surf Scoter"},
{value:"301", label:"Swainson's Hawk"},
{value:"1453", label:"Swainson's Thrush"},
{value:"1579", label:"Swainson's Warbler"},
{value:"262", label:"Swallow-tailed Kite"},
{value:"1724", label:"Swamp Sparrow"},
{value:"2056", label:"Swinhoe's Storm-Petrel"},
{value:"1535", label:"Tennessee Warbler"},
{value:"469", label:"Thayer's Gull"},
{value:"515", label:"Thick-billed Murre"},
{value:"1554", label:"Townsend's Warbler"},
{value:"1318", label:"Tree Swallow"},
{value:"234", label:"Tricolored Heron"},
{value:"1191", label:"Tropical Kingbird"},
{value:"25", label:"Trumpeter Swan"},
{value:"1343", label:"Tufted Titmouse"},
{value:"26", label:"Tundra Swan"},
{value:"256", label:"Turkey Vulture"},
{value:"410", label:"Upland Sandpiper"},
{value:"1450", label:"Veery"},
{value:"1156", label:"Vermilion Flycatcher"},
{value:"1710", label:"Vesper Sparrow"},
{value:"342", label:"Virginia Rail"},
{value:"1254", label:"Warbling Vireo"},
{value:"140", label:"Western Grebe"},
{value:"1195", label:"Western Kingbird"},
{value:"1780", label:"Western Meadowlark"},
{value:"430", label:"Western Sandpiper"},
{value:"1957", label:"Western Tanager"},
{value:"413", label:"Whimbrel"},
{value:"245", label:"White Ibis"},
{value:"73", label:"White Ibis"},
{value:"1348", label:"White-breasted Nuthatch"},
{value:"1728", label:"White-crowned Sparrow"},
{value:"1233", label:"White-eyed Vireo"},
{value:"1995", label:"White-faced Storm-Petrel"},
{value:"436", label:"White-rumped Sandpiper"},
{value:"195", label:"White-tailed Tropicbird"},
{value:"1726", label:"White-throated Sparrow"},
{value:"1856", label:"White-winged Crossbill"},
{value:"553", label:"White-winged Dove"},
{value:"64", label:"White-winged Scoter"},
{value:"498", label:"White-winged Tern"},
{value:"110", label:"Wild Turkey"},
{value:"405", label:"Willet"},
{value:"1141", label:"Willow Flycatcher"},
{value:"457", label:"Wilson's Phalarope"},
{value:"379", label:"Wilson's Plover"},
{value:"452", label:"Wilson's Snipe"},
{value:"181", label:"Wilson's Storm-Petrel"},
{value:"1601", label:"Wilson's Warbler"},
{value:"2066", label:"Winter Wren"},
{value:"31", label:"Wood Duck"},
{value:"253", label:"Wood Stork"},
{value:"1455", label:"Wood Thrush"},
{value:"1578", label:"Worm-eating Warbler"},
{value:"333", label:"Yellow Rail"},
{value:"1545", label:"Yellow Warbler"},
{value:"1138", label:"Yellow-bellied Flycatcher"},
{value:"956", label:"Yellow-bellied Sapsucker"},
{value:"644", label:"Yellow-billed Cuckoo"},
{value:"1618", label:"Yellow-breasted Chat"},
{value:"243", label:"Yellow-crowned Night-Heron"},
{value:"1781", label:"Yellow-headed Blackbird"},
{value:"468", label:"Yellow-legged Gull"},
{value:"142", label:"Yellow-nosed Albatross"},
{value:"1550", label:"Yellow-rumped Warbler"},
{value:"1247", label:"Yellow-throated Vireo"},
{value:"1557", label:"Yellow-throated Warbler"}];