var sppInfo = {"279":{"cn":"Cooper's Hawk","sn":"Accipiter cooperii","ss":"accipiter-cooperii","bnc":"201"},
"282":{"cn":"Northern Goshawk","sn":"Accipiter gentilis","ss":"accipiter-gentilis","bnc":"202"},
"278":{"cn":"Sharp-shinned Hawk","sn":"Accipiter striatus","ss":"accipiter-striatus","bnc":"200"},
"397":{"cn":"Spotted Sandpiper","sn":"Actitis macularius","ss":"actitis-macularius","bnc":"244"},
"141":{"cn":"Clark's Grebe","sn":"Aechmophorus clarkii","ss":"aechmophorus-clarkii","bnc":"11303"},
"140":{"cn":"Western Grebe","sn":"Aechmophorus occidentalis","ss":"aechmophorus-occidentalis","bnc":"104"},
"705":{"cn":"Northern Saw-whet Owl","sn":"Aegolius acadicus","ss":"aegolius-acadicus","bnc":"341"},
"1772":{"cn":"Red-winged Blackbird","sn":"Agelaius phoeniceus","ss":"agelaius-phoeniceus","bnc":"529"},
"1697":{"cn":"Bachman's Sparrow","sn":"Peucaea aestivalis","ss":"peucaea-aestivalis","bnc":"500"},
"31":{"cn":"Wood Duck","sn":"Aix sponsa","ss":"aix-sponsa","bnc":"162"},
"516":{"cn":"Razorbill","sn":"Alca torda","ss":"alca-torda","bnc":"315"},
"513":{"cn":"Dovekie","sn":"Alle alle","ss":"alle-alle","bnc":"313"},
"1718":{"cn":"Saltmarsh Sparrow","sn":"Ammodramus caudacutus","ss":"ammodramus-caudacutus","bnc":"513"},
"1717":{"cn":"Henslow's Sparrow","sn":"Ammodramus henslowii","ss":"ammodramus-henslowii","bnc":"511"},
"2040":{"cn":"Le Conte's Sparrow","sn":"Ammodramus leconteii","ss":"ammodramus-leconteii","bnc":"512"},
"1719":{"cn":"Seaside Sparrow","sn":"Ammodramus maritimus","ss":"ammodramus-maritimus","bnc":"514"},
"2041":{"cn":"Nelson's Sparrow","sn":"Ammodramus nelsoni","ss":"ammodramus-nelsoni","bnc":"515"},
"1716":{"cn":"Grasshopper Sparrow","sn":"Ammodramus savannarum","ss":"ammodramus-savannarum","bnc":"510"},
"46":{"cn":"Northern Pintail","sn":"Anas acuta","ss":"anas-acuta","bnc":"166"},
"35":{"cn":"American Wigeon","sn":"Anas americana","ss":"anas-americana","bnc":"173"},
"44":{"cn":"Northern Shoveler","sn":"Anas clypeata","ss":"anas-clypeata","bnc":"170"},
"49":{"cn":"Green-winged Teal","sn":"Anas crecca","ss":"anas-crecca","bnc":"163"},
"43":{"cn":"Cinnamon Teal","sn":"Anas cyanoptera","ss":"anas-cyanoptera","bnc":"169"},
"42":{"cn":"Blue-winged Teal","sn":"Anas discors","ss":"anas-discors","bnc":"168"},
"34":{"cn":"Eurasian Wigeon","sn":"Anas penelope","ss":"anas-penelope","bnc":"172"},
"37":{"cn":"Mallard","sn":"Anas platyrhynchos","ss":"anas-platyrhynchos","bnc":"165"},
"47":{"cn":"Garganey","sn":"Anas querquedula","ss":"anas-querquedula","bnc":"167"},
"36":{"cn":"American Black Duck","sn":"Anas rubripes","ss":"anas-rubripes","bnc":"164"},
"32":{"cn":"Gadwall","sn":"Anas strepera","ss":"anas-strepera","bnc":"171"},
"213":{"cn":"Anhinga","sn":"Anhinga anhinga","ss":"anhinga-anhinga","bnc":"132"},
"482":{"cn":"Brown Noddy","sn":"Anous stolidus","ss":"anous-stolidus","bnc":"311"},
"14":{"cn":"Greater White-fronted Goose","sn":"Anser albifrons","ss":"anser-albifrons","bnc":"157"},
"1521":{"cn":"American Pipit","sn":"Anthus rubescens","ss":"anthus-rubescens","bnc":"427"},
"1522":{"cn":"Sprague's Pipit","sn":"Anthus spragueii","ss":"anthus-spragueii","bnc":"428"},
"310":{"cn":"Golden Eagle","sn":"Aquila chrysaetos","ss":"aquila-chrysaetos","bnc":"208"},
"364":{"cn":"Limpkin","sn":"Aramus guarauna","ss":"aramus-guarauna","bnc":"226"},
"864":{"cn":"Ruby-throated Hummingbird","sn":"Archilochus colubris","ss":"archilochus-colubris","bnc":"349"},
"227":{"cn":"Great Egret","sn":"Ardea alba","ss":"ardea-alba","bnc":"138"},
"224":{"cn":"Great Blue Heron","sn":"Ardea herodias","ss":"ardea-herodias","bnc":"136"},
"423":{"cn":"Ruddy Turnstone","sn":"Arenaria interpres","ss":"arenaria-interpres","bnc":"253"},
"701":{"cn":"Short-eared Owl","sn":"Asio flammeus","ss":"asio-flammeus","bnc":"340"},
"699":{"cn":"Long-eared Owl","sn":"Asio otus","ss":"asio-otus","bnc":"339"},
"56":{"cn":"Lesser Scaup","sn":"Aythya affinis","ss":"aythya-affinis","bnc":"178"},
"51":{"cn":"Redhead","sn":"Aythya americana","ss":"aythya-americana","bnc":"175"},
"53":{"cn":"Ring-necked Duck","sn":"Aythya collaris","ss":"aythya-collaris","bnc":"176"},
"55":{"cn":"Greater Scaup","sn":"Aythya marila","ss":"aythya-marila","bnc":"177"},
"50":{"cn":"Canvasback","sn":"Aythya valisineria","ss":"aythya-valisineria","bnc":"174"},
"1343":{"cn":"Tufted Titmouse","sn":"Baeolophus bicolor","ss":"baeolophus-bicolor","bnc":"397"},
"410":{"cn":"Upland Sandpiper","sn":"Bartramia longicauda","ss":"bartramia-longicauda","bnc":"245"},
"1525":{"cn":"Cedar Waxwing","sn":"Bombycilla cedrorum","ss":"bombycilla-cedrorum","bnc":"429"},
"98":{"cn":"Ruffed Grouse","sn":"Bonasa umbellus","ss":"bonasa-umbellus","bnc":"214"},
"218":{"cn":"American Bittern","sn":"Botaurus lentiginosus","ss":"botaurus-lentiginosus","bnc":"134"},
"19":{"cn":"Brant","sn":"Branta bernicla","ss":"branta-bernicla","bnc":"160"},
"22":{"cn":"Canada Goose","sn":"Branta canadensis","ss":"branta-canadensis","bnc":"161"},
"21":{"cn":"Cackling Goose","sn":"Branta hutchinsii","ss":"branta-hutchinsii","bnc":"12179"},
"20":{"cn":"Barnacle Goose","sn":"Branta leucopsis","ss":"branta-leucopsis","bnc":"12210"},
"682":{"cn":"Snowy Owl","sn":"Bubo scandiacus","ss":"bubo-scandiacus","bnc":"336"},
"681":{"cn":"Great Horned Owl","sn":"Bubo virginianus","ss":"bubo-virginianus","bnc":"335"},
"236":{"cn":"Cattle Egret","sn":"Bubulcus ibis","ss":"bubulcus-ibis","bnc":"143"},
"67":{"cn":"Bufflehead","sn":"Bucephala albeola","ss":"bucephala-albeola","bnc":"188"},
"68":{"cn":"Common Goldeneye","sn":"Bucephala clangula","ss":"bucephala-clangula","bnc":"186"},
"163":{"cn":"Bulwer's Petrel","sn":"Bulweria bulwerii","ss":"bulweria-bulwerii","bnc":"112"},
"305":{"cn":"Red-tailed Hawk","sn":"Buteo jamaicensis","ss":"buteo-jamaicensis","bnc":"206"},
"307":{"cn":"Rough-legged Hawk","sn":"Buteo lagopus","ss":"buteo-lagopus","bnc":"207"},
"296":{"cn":"Red-shouldered Hawk","sn":"Buteo lineatus","ss":"buteo-lineatus","bnc":"203"},
"298":{"cn":"Broad-winged Hawk","sn":"Buteo platypterus","ss":"buteo-platypterus","bnc":"204"},
"301":{"cn":"Swainson's Hawk","sn":"Buteo swainsoni","ss":"buteo-swainsoni","bnc":"205"},
"238":{"cn":"Green Heron","sn":"Butorides virescens","ss":"butorides-virescens","bnc":"144"},
"1714":{"cn":"Lark Bunting","sn":"Calamospiza melanocorys","ss":"calamospiza-melanocorys","bnc":"507"},
"1733":{"cn":"Lapland Longspur","sn":"Calcarius lapponicus","ss":"calcarius-lapponicus","bnc":"524"},
"428":{"cn":"Sanderling","sn":"Calidris alba","ss":"calidris-alba","bnc":"255"},
"442":{"cn":"Dunlin","sn":"Calidris alpina","ss":"calidris-alpina","bnc":"264"},
"437":{"cn":"Baird's Sandpiper","sn":"Calidris bairdii","ss":"calidris-bairdii","bnc":"261"},
"427":{"cn":"Red Knot","sn":"Calidris canutus","ss":"calidris-canutus","bnc":"254"},
"443":{"cn":"Curlew Sandpiper","sn":"Calidris ferruginea","ss":"calidris-ferruginea","bnc":"265"},
"436":{"cn":"White-rumped Sandpiper","sn":"Calidris fuscicollis","ss":"calidris-fuscicollis","bnc":"260"},
"444":{"cn":"Stilt Sandpiper","sn":"Calidris himantopus","ss":"calidris-himantopus","bnc":"266"},
"440":{"cn":"Purple Sandpiper","sn":"Calidris maritima","ss":"calidris-maritima","bnc":"263"},
"430":{"cn":"Western Sandpiper","sn":"Calidris mauri","ss":"calidris-mauri","bnc":"257"},
"438":{"cn":"Pectoral Sandpiper","sn":"Calidris melanotos","ss":"calidris-melanotos","bnc":"262"},
"432":{"cn":"Little Stint","sn":"Calidris minuta","ss":"calidris-minuta","bnc":"258"},
"435":{"cn":"Least Sandpiper","sn":"Calidris minutilla","ss":"calidris-minutilla","bnc":"259"},
"429":{"cn":"Semipalmated Sandpiper","sn":"Calidris pusilla","ss":"calidris-pusilla","bnc":"256"},
"167":{"cn":"Cory's Shearwater","sn":"Calonectris diomedea","ss":"calonectris-diomedea","bnc":"113"},
"168":{"cn":"Cape Verde Shearwater","sn":"Calonectris edwardsii","ss":"calonectris-edwardsii","bnc":"11304"},
"718":{"cn":"Chuck-will's-widow","sn":"Antrostomus carolinensis","ss":"antrostomus-carolinensis","bnc":"345"},
"724":{"cn":"Eastern Whip-poor-will","sn":"Antrostomus vociferus","ss":"antrostomus-vociferus","bnc":"346"},
"1755":{"cn":"Northern Cardinal","sn":"Cardinalis cardinalis","ss":"cardinalis-cardinalis","bnc":"488"},
"1857":{"cn":"Common Redpoll","sn":"Acanthis flammea","ss":"acanthis-flammea","bnc":"548"},
"1860":{"cn":"Pine Siskin","sn":"Spinus pinus","ss":"spinus-pinus","bnc":"549"},
"1868":{"cn":"American Goldfinch","sn":"Spinus tristis","ss":"spinus-tristis","bnc":"551"},
"10371":{"cn":"House Finch","sn":"Haemorhous mexicanus","ss":"haemorhous-mexicanus","bnc":"544"},
"10351":{"cn":"Purple Finch","sn":"Haemorhous purpureus","ss":"haemorhous-purpureus","bnc":"543"},
"256":{"cn":"Turkey Vulture","sn":"Cathartes aura","ss":"cathartes-aura","bnc":"153"},
"1450":{"cn":"Veery","sn":"Catharus fuscescens","ss":"catharus-fuscescens","bnc":"415"},
"1454":{"cn":"Hermit Thrush","sn":"Catharus guttatus","ss":"catharus-guttatus","bnc":"418"},
"1451":{"cn":"Gray-cheeked Thrush","sn":"Catharus minimus","ss":"catharus-minimus","bnc":"416"},
"1453":{"cn":"Swainson's Thrush","sn":"Catharus ustulatus","ss":"catharus-ustulatus","bnc":"417"},
"1351":{"cn":"Brown Creeper","sn":"Certhia americana","ss":"certhia-americana","bnc":"401"},
"912":{"cn":"Belted Kingfisher","sn":"Megaceryle alcyon","ss":"megaceryle-alcyon","bnc":"353"},
"741":{"cn":"Chimney Swift","sn":"Chaetura pelagica","ss":"chaetura-pelagica","bnc":"347"},
"378":{"cn":"Snowy Plover","sn":"Charadrius nivosus","ss":"charadrius-nivosus","bnc":"231"},
"382":{"cn":"Piping Plover","sn":"Charadrius melodus","ss":"charadrius-melodus","bnc":"234"},
"381":{"cn":"Semipalmated Plover","sn":"Charadrius semipalmatus","ss":"charadrius-semipalmatus","bnc":"233"},
"384":{"cn":"Killdeer","sn":"Charadrius vociferus","ss":"charadrius-vociferus","bnc":"235"},
"379":{"cn":"Wilson's Plover","sn":"Charadrius wilsonia","ss":"charadrius-wilsonia","bnc":"232"},
"17":{"cn":"Snow Goose","sn":"Chen caerulescens","ss":"chen-caerulescens","bnc":"158"},
"18":{"cn":"Ross's Goose","sn":"Chen rossii","ss":"chen-rossii","bnc":"159"},
"498":{"cn":"White-winged Tern","sn":"Chlidonias leucopterus","ss":"chlidonias-leucopterus","bnc":"309"},
"497":{"cn":"Black Tern","sn":"Chlidonias niger","ss":"chlidonias-niger","bnc":"310"},
"1711":{"cn":"Lark Sparrow","sn":"Chondestes grammacus","ss":"chondestes-grammacus","bnc":"506"},
"710":{"cn":"Antillean Nighthawk","sn":"Chordeiles gundlachii","ss":"chordeiles-gundlachii","bnc":"344"},
"709":{"cn":"Common Nighthawk","sn":"Chordeiles minor","ss":"chordeiles-minor","bnc":"343"},
"274":{"cn":"Northern Harrier","sn":"Circus cyaneus","ss":"circus-cyaneus","bnc":"199"},
"1391":{"cn":"Marsh Wren","sn":"Cistothorus palustris","ss":"cistothorus-palustris","bnc":"408"},
"1390":{"cn":"Sedge Wren","sn":"Cistothorus platensis","ss":"cistothorus-platensis","bnc":"407"},
"66":{"cn":"Long-tailed Duck","sn":"Clangula hyemalis","ss":"clangula-hyemalis","bnc":"182"},
"1875":{"cn":"Evening Grosbeak","sn":"Coccothraustes vespertinus","ss":"coccothraustes-vespertinus","bnc":"552"},
"644":{"cn":"Yellow-billed Cuckoo","sn":"Coccyzus americanus","ss":"coccyzus-americanus","bnc":"330"},
"648":{"cn":"Black-billed Cuckoo","sn":"Coccyzus erythropthalmus","ss":"coccyzus-erythropthalmus","bnc":"329"},
"979":{"cn":"Northern Flicker","sn":"Colaptes auratus","ss":"colaptes-auratus","bnc":"361"},
"122":{"cn":"Northern Bobwhite","sn":"Colinus virginianus","ss":"colinus-virginianus","bnc":"216"},
"536":{"cn":"Rock Pigeon","sn":"Columba livia","ss":"columba-livia","bnc":"319"},
"560":{"cn":"Common Ground-Dove","sn":"Columbina passerina","ss":"columbina-passerina","bnc":"325"},
"1127":{"cn":"Olive-sided Flycatcher","sn":"Contopus cooperi","ss":"contopus-cooperi","bnc":"364"},
"1132":{"cn":"Eastern Wood-Pewee","sn":"Contopus virens","ss":"contopus-virens","bnc":"365"},
"255":{"cn":"Black Vulture","sn":"Coragyps atratus","ss":"coragyps-atratus","bnc":"152"},
"1296":{"cn":"American Crow","sn":"Corvus brachyrhynchos","ss":"corvus-brachyrhynchos","bnc":"391"},
"1307":{"cn":"Common Raven","sn":"Corvus corax","ss":"corvus-corax","bnc":"393"},
"1304":{"cn":"Fish Crow","sn":"Corvus ossifragus","ss":"corvus-ossifragus","bnc":"392"},
"333":{"cn":"Yellow Rail","sn":"Coturnicops noveboracensis","ss":"coturnicops-noveboracensis","bnc":"217"},
"1270":{"cn":"Blue Jay","sn":"Cyanocitta cristata","ss":"cyanocitta-cristata","bnc":"390"},
"25":{"cn":"Trumpeter Swan","sn":"Cygnus buccinator","ss":"cygnus-buccinator","bnc":"12211"},
"26":{"cn":"Tundra Swan","sn":"Cygnus columbianus","ss":"cygnus-columbianus","bnc":"155"},
"24":{"cn":"Mute Swan","sn":"Cygnus olor","ss":"cygnus-olor","bnc":"156"},
"1549":{"cn":"Black-throated Blue Warbler","sn":"Setophaga caerulescens","ss":"setophaga-caerulescens","bnc":"454"},
"1568":{"cn":"Bay-breasted Warbler","sn":"Setophaga castanea","ss":"setophaga-castanea","bnc":"466"},
"1570":{"cn":"Cerulean Warbler","sn":"Setophaga cerulea","ss":"setophaga-cerulea","bnc":"468"},
"1550":{"cn":"Yellow-rumped Warbler","sn":"Setophaga coronata","ss":"setophaga-coronata","bnc":"455"},
"1565":{"cn":"Prairie Warbler","sn":"Setophaga discolor","ss":"setophaga-discolor","bnc":"464"},
"1557":{"cn":"Yellow-throated Warbler","sn":"Setophaga dominica","ss":"setophaga-dominica","bnc":"461"},
"1556":{"cn":"Blackburnian Warbler","sn":"Setophaga fusca","ss":"setophaga-fusca","bnc":"460"},
"1547":{"cn":"Magnolia Warbler","sn":"Setophaga magnolia","ss":"setophaga-magnolia","bnc":"452"},
"1567":{"cn":"Palm Warbler","sn":"Setophaga palmarum","ss":"setophaga-palmarum","bnc":"465"},
"1546":{"cn":"Chestnut-sided Warbler","sn":"Setophaga pensylvanica","ss":"setophaga-pensylvanica","bnc":"451"},
"1545":{"cn":"Yellow Warbler","sn":"Setophaga petechia","ss":"setophaga-petechia","bnc":"450"},
"1563":{"cn":"Pine Warbler","sn":"Setophaga pinus","ss":"setophaga-pinus","bnc":"462"},
"1569":{"cn":"Blackpoll Warbler","sn":"Setophaga striata","ss":"setophaga-striata","bnc":"467"},
"1548":{"cn":"Cape May Warbler","sn":"Setophaga tigrina","ss":"setophaga-tigrina","bnc":"453"},
"1554":{"cn":"Townsend's Warbler","sn":"Setophaga townsendi","ss":"setophaga-townsendi","bnc":"457"},
"1553":{"cn":"Black-throated Green Warbler","sn":"Setophaga virens","ss":"setophaga-virens","bnc":"458"},
"1771":{"cn":"Bobolink","sn":"Dolichonyx oryzivorus","ss":"dolichonyx-oryzivorus","bnc":"528"},
"985":{"cn":"Pileated Woodpecker","sn":"Dryocopus pileatus","ss":"dryocopus-pileatus","bnc":"362"},
"1485":{"cn":"Gray Catbird","sn":"Dumetella carolinensis","ss":"dumetella-carolinensis","bnc":"422"},
"233":{"cn":"Little Blue Heron","sn":"Egretta caerulea","ss":"egretta-caerulea","bnc":"140"},
"233":{"cn":"Little Blue Heron","sn":"Egretta caerulea","ss":"egretta-caerulea","bnc":"140"},
"235":{"cn":"Reddish Egret","sn":"Egretta rufescens","ss":"egretta-rufescens","bnc":"142"},
"232":{"cn":"Snowy Egret","sn":"Egretta thula","ss":"egretta-thula","bnc":"139"},
"234":{"cn":"Tricolored Heron","sn":"Egretta tricolor","ss":"egretta-tricolor","bnc":"141"},
"262":{"cn":"Swallow-tailed Kite","sn":"Elanoides forficatus","ss":"elanoides-forficatus","bnc":"195"},
"1140":{"cn":"Alder Flycatcher","sn":"Empidonax alnorum","ss":"empidonax-alnorum","bnc":"368"},
"1138":{"cn":"Yellow-bellied Flycatcher","sn":"Empidonax flaviventris","ss":"empidonax-flaviventris","bnc":"366"},
"1143":{"cn":"Least Flycatcher","sn":"Empidonax minimus","ss":"empidonax-minimus","bnc":"370"},
"1141":{"cn":"Willow Flycatcher","sn":"Empidonax traillii","ss":"empidonax-traillii","bnc":"369"},
"1139":{"cn":"Acadian Flycatcher","sn":"Empidonax virescens","ss":"empidonax-virescens","bnc":"367"},
"1310":{"cn":"Horned Lark","sn":"Eremophila alpestris","ss":"eremophila-alpestris","bnc":"382"},
"245":{"cn":"White Ibis","sn":"Eudocimus albus","ss":"eudocimus-albus","bnc":"147"},
"1784":{"cn":"Rusty Blackbird","sn":"Euphagus carolinus","ss":"euphagus-carolinus","bnc":"533"},
"1785":{"cn":"Brewer's Blackbird","sn":"Euphagus cyanocephalus","ss":"euphagus-cyanocephalus","bnc":"534"},
"325":{"cn":"Merlin","sn":"Falco columbarius","ss":"falco-columbarius","bnc":"210"},
"331":{"cn":"Peregrine Falcon","sn":"Falco peregrinus","ss":"falco-peregrinus","bnc":"211"},
"323":{"cn":"American Kestrel","sn":"Falco sparverius","ss":"falco-sparverius","bnc":"209"},
"532":{"cn":"Atlantic Puffin","sn":"Fratercula arctica","ss":"fratercula-arctica","bnc":"318"},
"214":{"cn":"Magnificent Frigatebird","sn":"Fregata magnificens","ss":"fregata-magnificens","bnc":"133"},
"183":{"cn":"Black-bellied Storm-Petrel","sn":"Fregetta tropica","ss":"fregetta-tropica","bnc":"12213"},
"360":{"cn":"American Coot","sn":"Fulica americana","ss":"fulica-americana","bnc":"225"},
"1983":{"cn":"Northern Fulmar","sn":"Fulmarus glacialis","ss":"fulmarus-glacialis","bnc":"107"},
"452":{"cn":"Wilson's Snipe","sn":"Gallinago delicata","ss":"gallinago-delicata","bnc":"271"},
"357":{"cn":"Common Gallinule","sn":"Gallinula galeata","ss":"gallinula-galeata","bnc":"224"},
"136":{"cn":"Common Loon","sn":"Gavia immer","ss":"gavia-immer","bnc":"98"},
"135":{"cn":"Pacific Loon","sn":"Gavia pacifica","ss":"gavia-pacifica","bnc":"99"},
"134":{"cn":"Red-throated Loon","sn":"Gavia stellata","ss":"gavia-stellata","bnc":"97"},
"494":{"cn":"Gull-billed Tern","sn":"Gelochelidon nilotica","ss":"gelochelidon-nilotica","bnc":"298"},
"1587":{"cn":"Common Yellowthroat","sn":"Geothlypis trichas","ss":"geothlypis-trichas","bnc":"480"},
"365":{"cn":"Sandhill Crane","sn":"Grus canadensis","ss":"grus-canadensis","bnc":"227"},
"388":{"cn":"American Oystercatcher","sn":"Haematopus palliatus","ss":"haematopus-palliatus","bnc":"236"},
"270":{"cn":"Bald Eagle","sn":"Haliaeetus leucocephalus","ss":"haliaeetus-leucocephalus","bnc":"198"},
"1578":{"cn":"Worm-eating Warbler","sn":"Helmitheros vermivorum","ss":"helmitheros-vermivorum","bnc":"472"},
"391":{"cn":"Black-necked Stilt","sn":"Himantopus mexicanus","ss":"himantopus-mexicanus","bnc":"237"},
"1331":{"cn":"Barn Swallow","sn":"Hirundo rustica","ss":"hirundo-rustica","bnc":"389"},
"61":{"cn":"Harlequin Duck","sn":"Histrionicus histrionicus","ss":"histrionicus-histrionicus","bnc":"181"},
"182":{"cn":"European Storm-Petrel","sn":"Hydrobates pelagicus","ss":"hydrobates-pelagicus","bnc":"12212"},
"495":{"cn":"Caspian Tern","sn":"Hydroprogne caspia","ss":"hydroprogne-caspia","bnc":"299"},
"1455":{"cn":"Wood Thrush","sn":"Hylocichla mustelina","ss":"hylocichla-mustelina","bnc":"420"},
"1618":{"cn":"Yellow-breasted Chat","sn":"Icteria virens","ss":"icteria-virens","bnc":"484"},
"1817":{"cn":"Baltimore Oriole","sn":"Icterus galbula","ss":"icterus-galbula","bnc":"540"},
"1804":{"cn":"Orchard Oriole","sn":"Icterus spurius","ss":"icterus-spurius","bnc":"539"},
"2038":{"cn":"Mississippi Kite","sn":"Ictinia mississippiensis","ss":"ictinia-mississippiensis","bnc":"197"},
"220":{"cn":"Least Bittern","sn":"Ixobrychus exilis","ss":"ixobrychus-exilis","bnc":"135"},
"1730":{"cn":"Dark-eyed Junco","sn":"Junco hyemalis","ss":"junco-hyemalis","bnc":"523"},
"1231":{"cn":"Northern Shrike","sn":"Lanius excubitor","ss":"lanius-excubitor","bnc":"430"},
"1230":{"cn":"Loggerhead Shrike","sn":"Lanius ludovicianus","ss":"lanius-ludovicianus","bnc":"431"},
"467":{"cn":"Herring Gull","sn":"Larus argentatus","ss":"larus-argentatus","bnc":"289"},
"1990":{"cn":"Laughing Gull","sn":"Leucophaeus atricilla","ss":"leucophaeus-atricilla","bnc":"281"},
"468":{"cn":"Yellow-legged Gull","sn":"Larus michahellis","ss":"larus-michahellis","bnc":"290"},
"466":{"cn":"California Gull","sn":"Larus californicus","ss":"larus-californicus","bnc":"288"},
"464":{"cn":"Mew Gull","sn":"Larus canus","ss":"larus-canus","bnc":"286"},
"463":{"cn":"Black-tailed Gull","sn":"Larus crassirostris","ss":"larus-crassirostris","bnc":"12216"},
"465":{"cn":"Ring-billed Gull","sn":"Larus delawarensis","ss":"larus-delawarensis","bnc":"287"},
"471":{"cn":"Lesser Black-backed Gull","sn":"Larus fuscus","ss":"larus-fuscus","bnc":"293"},
"470":{"cn":"Iceland Gull","sn":"Larus glaucoides","ss":"larus-glaucoides","bnc":"292"},
"476":{"cn":"Glaucous Gull","sn":"Larus hyperboreus","ss":"larus-hyperboreus","bnc":"294"},
"477":{"cn":"Great Black-backed Gull","sn":"Larus marinus","ss":"larus-marinus","bnc":"295"},
"461":{"cn":"Little Gull","sn":"Hydrocoloeus minutus","ss":"hydrocoloeus-minutus","bnc":"283"},
"1993":{"cn":"Bonaparte's Gull","sn":"Chroicocephalus philadelphia","ss":"chroicocephalus-philadelphia","bnc":"285"},
"479":{"cn":"Franklin's Gull","sn":"Leucophaeus pipixcan","ss":"leucophaeus-pipixcan","bnc":"282"},
"1994":{"cn":"Black-headed Gull","sn":"Chroicocephalus ridibundus","ss":"chroicocephalus-ridibundus","bnc":"284"},
"472":{"cn":"Slaty-backed Gull","sn":"Larus schistisagus","ss":"larus-schistisagus","bnc":"12217"},
"469":{"cn":"Thayer's Gull","sn":"Larus thayeri","ss":"larus-thayeri","bnc":"291"},
"338":{"cn":"Black Rail","sn":"Laterallus jamaicensis","ss":"laterallus-jamaicensis","bnc":"218"},
"449":{"cn":"Short-billed Dowitcher","sn":"Limnodromus griseus","ss":"limnodromus-griseus","bnc":"269"},
"450":{"cn":"Long-billed Dowitcher","sn":"Limnodromus scolopaceus","ss":"limnodromus-scolopaceus","bnc":"270"},
"1579":{"cn":"Swainson's Warbler","sn":"Limnothlypis swainsonii","ss":"limnothlypis-swainsonii","bnc":"473"},
"422":{"cn":"Marbled Godwit","sn":"Limosa fedoa","ss":"limosa-fedoa","bnc":"252"},
"420":{"cn":"Hudsonian Godwit","sn":"Limosa haemastica","ss":"limosa-haemastica","bnc":"250"},
"421":{"cn":"Bar-tailed Godwit","sn":"Limosa lapponica","ss":"limosa-lapponica","bnc":"251"},
"419":{"cn":"Black-tailed Godwit","sn":"Limosa limosa","ss":"limosa-limosa","bnc":"249"},
"71":{"cn":"Hooded Merganser","sn":"Lophodytes cucullatus","ss":"lophodytes-cucullatus","bnc":"189"},
"1854":{"cn":"Red Crossbill","sn":"Loxia curvirostra","ss":"loxia-curvirostra","bnc":"545"},
"1856":{"cn":"White-winged Crossbill","sn":"Loxia leucoptera","ss":"loxia-leucoptera","bnc":"547"},
"669":{"cn":"Eastern Screech-Owl","sn":"Megascops asio","ss":"megascops-asio","bnc":"334"},
"953":{"cn":"Red-bellied Woodpecker","sn":"Melanerpes carolinus","ss":"melanerpes-carolinus","bnc":"355"},
"940":{"cn":"Red-headed Woodpecker","sn":"Melanerpes erythrocephalus","ss":"melanerpes-erythrocephalus","bnc":"354"},
"64":{"cn":"White-winged Scoter","sn":"Melanitta fusca","ss":"melanitta-fusca","bnc":"185"},
"65":{"cn":"Black Scoter","sn":"Melanitta americana","ss":"melanitta-americana","bnc":"183"},
"63":{"cn":"Surf Scoter","sn":"Melanitta perspicillata","ss":"melanitta-perspicillata","bnc":"184"},
"110":{"cn":"Wild Turkey","sn":"Meleagris gallopavo","ss":"meleagris-gallopavo","bnc":"215"},
"1724":{"cn":"Swamp Sparrow","sn":"Melospiza georgiana","ss":"melospiza-georgiana","bnc":"519"},
"1723":{"cn":"Lincoln's Sparrow","sn":"Melospiza lincolnii","ss":"melospiza-lincolnii","bnc":"518"},
"1722":{"cn":"Song Sparrow","sn":"Melospiza melodia","ss":"melospiza-melodia","bnc":"517"},
"72":{"cn":"Common Merganser","sn":"Mergus merganser","ss":"mergus-merganser","bnc":"190"},
"73":{"cn":"Red-breasted Merganser","sn":"Mergus serrator","ss":"mergus-serrator","bnc":"191"},
"73":{"cn":"White Ibis","sn":"Mergus serrator","ss":"mergus-serrator","bnc":"191"},
"1487":{"cn":"Northern Mockingbird","sn":"Mimus polyglottos","ss":"mimus-polyglottos","bnc":"423"},
"1575":{"cn":"Black-and-white Warbler","sn":"Mniotilta varia","ss":"mniotilta-varia","bnc":"469"},
"1795":{"cn":"Brown-headed Cowbird","sn":"Molothrus ater","ss":"molothrus-ater","bnc":"538"},
"1793":{"cn":"Shiny Cowbird","sn":"Molothrus bonariensis","ss":"molothrus-bonariensis","bnc":"537"},
"204":{"cn":"Northern Gannet","sn":"Morus bassanus","ss":"morus-bassanus","bnc":"127"},
"253":{"cn":"Wood Stork","sn":"Mycteria americana","ss":"mycteria-americana","bnc":"151"},
"1167":{"cn":"Ash-throated Flycatcher","sn":"Myiarchus cinerascens","ss":"myiarchus-cinerascens","bnc":"374"},
"1169":{"cn":"Great Crested Flycatcher","sn":"Myiarchus crinitus","ss":"myiarchus-crinitus","bnc":"375"},
"418":{"cn":"Long-billed Curlew","sn":"Numenius americanus","ss":"numenius-americanus","bnc":"248"},
"413":{"cn":"Whimbrel","sn":"Numenius phaeopus","ss":"numenius-phaeopus","bnc":"247"},
"243":{"cn":"Yellow-crowned Night-Heron","sn":"Nyctanassa violacea","ss":"nyctanassa-violacea","bnc":"146"},
"242":{"cn":"Black-crowned Night-Heron","sn":"Nycticorax nycticorax","ss":"nycticorax-nycticorax","bnc":"145"},
"181":{"cn":"Wilson's Storm-Petrel","sn":"Oceanites oceanicus","ss":"oceanites-oceanicus","bnc":"119"},
"188":{"cn":"Band-rumped Storm-Petrel","sn":"Oceanodroma castro","ss":"oceanodroma-castro","bnc":"122"},
"186":{"cn":"Leach's Storm-Petrel","sn":"Oceanodroma leucorhoa","ss":"oceanodroma-leucorhoa","bnc":"121"},
"2056":{"cn":"Swinhoe's Storm-Petrel","sn":"Oceanodroma monorhis","ss":"oceanodroma-monorhis","bnc":"12214"},
"1426":{"cn":"Northern Wheatear","sn":"Oenanthe oenanthe","ss":"oenanthe-oenanthe","bnc":"412"},
"488":{"cn":"Bridled Tern","sn":"Onychoprion anaethetus","ss":"onychoprion-anaethetus","bnc":"307"},
"486":{"cn":"Sooty Tern","sn":"Onychoprion fuscatus","ss":"onychoprion-fuscatus","bnc":"308"},
"1584":{"cn":"Connecticut Warbler","sn":"Oporornis agilis","ss":"oporornis-agilis","bnc":"478"},
"1583":{"cn":"Kentucky Warbler","sn":"Geothlypis formosa","ss":"geothlypis-formosa","bnc":"477"},
"1585":{"cn":"Mourning Warbler","sn":"Geothlypis philadelphia","ss":"geothlypis-philadelphia","bnc":"479"},
"1586":{"cn":"MacGillivray's Warbler","sn":"Geothlypis tolmiei","ss":"geothlypis-tolmiei","bnc":"12228"},
"1491":{"cn":"Sage Thrasher","sn":"Oreoscoptes montanus","ss":"oreoscoptes-montanus","bnc":"424"},
"75":{"cn":"Ruddy Duck","sn":"Oxyura jamaicensis","ss":"oxyura-jamaicensis","bnc":"192"},
"2005":{"cn":"Osprey","sn":"Pandion haliaetus","ss":"pandion-haliaetus","bnc":"194"},
"1543":{"cn":"Northern Parula","sn":"Setophaga americana","ss":"setophaga-americana","bnc":"449"},
"1907":{"cn":"House Sparrow","sn":"Passer domesticus","ss":"passer-domesticus","bnc":"553"},
"1715":{"cn":"Savannah Sparrow","sn":"Passerculus sandwichensis","ss":"passerculus-sandwichensis","bnc":"508"},
"1721":{"cn":"Fox Sparrow","sn":"Passerella iliaca","ss":"passerella-iliaca","bnc":"516"},
"1763":{"cn":"Blue Grosbeak","sn":"Passerina caerulea","ss":"passerina-caerulea","bnc":"491"},
"1769":{"cn":"Painted Bunting","sn":"Passerina ciris","ss":"passerina-ciris","bnc":"495"},
"1765":{"cn":"Indigo Bunting","sn":"Passerina cyanea","ss":"passerina-cyanea","bnc":"493"},
"1995":{"cn":"White-faced Storm-Petrel","sn":"Pelagodroma marina","ss":"pelagodroma-marina","bnc":"120"},
"205":{"cn":"American White Pelican","sn":"Pelecanus erythrorhynchos","ss":"pelecanus-erythrorhynchos","bnc":"128"},
"206":{"cn":"Brown Pelican","sn":"Pelecanus occidentalis","ss":"pelecanus-occidentalis","bnc":"129"},
"1330":{"cn":"Cave Swallow","sn":"Petrochelidon fulva","ss":"petrochelidon-fulva","bnc":"388"},
"1329":{"cn":"Cliff Swallow","sn":"Petrochelidon pyrrhonota","ss":"petrochelidon-pyrrhonota","bnc":"387"},
"196":{"cn":"Red-billed Tropicbird","sn":"Phaethon aethereus","ss":"phaethon-aethereus","bnc":"124"},
"195":{"cn":"White-tailed Tropicbird","sn":"Phaethon lepturus","ss":"phaethon-lepturus","bnc":"123"},
"209":{"cn":"Double-crested Cormorant","sn":"Phalacrocorax auritus","ss":"phalacrocorax-auritus","bnc":"131"},
"210":{"cn":"Great Cormorant","sn":"Phalacrocorax carbo","ss":"phalacrocorax-carbo","bnc":"130"},
"459":{"cn":"Red Phalarope","sn":"Phalaropus fulicarius","ss":"phalaropus-fulicarius","bnc":"275"},
"458":{"cn":"Red-necked Phalarope","sn":"Phalaropus lobatus","ss":"phalaropus-lobatus","bnc":"274"},
"457":{"cn":"Wilson's Phalarope","sn":"Phalaropus tricolor","ss":"phalaropus-tricolor","bnc":"273"},
"1759":{"cn":"Rose-breasted Grosbeak","sn":"Pheucticus ludovicianus","ss":"pheucticus-ludovicianus","bnc":"489"},
"448":{"cn":"Ruff","sn":"Philomachus pugnax","ss":"philomachus-pugnax","bnc":"268"},
"967":{"cn":"Red-cockaded Woodpecker","sn":"Picoides borealis","ss":"picoides-borealis","bnc":"360"},
"963":{"cn":"Downy Woodpecker","sn":"Picoides pubescens","ss":"picoides-pubescens","bnc":"358"},
"964":{"cn":"Hairy Woodpecker","sn":"Picoides villosus","ss":"picoides-villosus","bnc":"359"},
"1689":{"cn":"Eastern Towhee","sn":"Pipilo erythrophthalmus","ss":"pipilo-erythrophthalmus","bnc":"498"},
"1957":{"cn":"Western Tanager","sn":"Piranga ludoviciana","ss":"piranga-ludoviciana","bnc":"487"},
"1956":{"cn":"Scarlet Tanager","sn":"Piranga olivacea","ss":"piranga-olivacea","bnc":"486"},
"1955":{"cn":"Summer Tanager","sn":"Piranga rubra","ss":"piranga-rubra","bnc":"485"},
"251":{"cn":"Roseate Spoonbill","sn":"Platalea ajaja","ss":"platalea-ajaja","bnc":"150"},
"1744":{"cn":"Snow Bunting","sn":"Plectrophenax nivalis","ss":"plectrophenax-nivalis","bnc":"527"},
"247":{"cn":"Glossy Ibis","sn":"Eudocimus falcinellus","ss":"eudocimus-falcinellus","bnc":"148"},
"373":{"cn":"American Golden-Plover","sn":"Pluvialis dominica","ss":"pluvialis-dominica","bnc":"230"},
"371":{"cn":"Black-bellied Plover","sn":"Pluvialis squatarola","ss":"pluvialis-squatarola","bnc":"229"},
"1986":{"cn":"Horned Grebe","sn":"Podiceps auritus","ss":"podiceps-auritus","bnc":"101"},
"1987":{"cn":"Red-necked Grebe","sn":"Podiceps grisegena","ss":"podiceps-grisegena","bnc":"102"},
"1985":{"cn":"Eared Grebe","sn":"Podiceps nigricollis","ss":"podiceps-nigricollis","bnc":"103"},
"138":{"cn":"Pied-billed Grebe","sn":"Podilymbus podiceps","ss":"podilymbus-podiceps","bnc":"100"},
"1334":{"cn":"Black-capped Chickadee","sn":"Poecile atricapillus","ss":"poecile-atricapillus","bnc":"394"},
"1333":{"cn":"Carolina Chickadee","sn":"Poecile carolinensis","ss":"poecile-carolinensis","bnc":"396"},
"2010":{"cn":"Blue-gray Gnatcatcher","sn":"Polioptila caerulea","ss":"polioptila-caerulea","bnc":"411"},
"1710":{"cn":"Vesper Sparrow","sn":"Pooecetes gramineus","ss":"pooecetes-gramineus","bnc":"505"},
"9871":{"cn":"Purple Gallinule","sn":"Porphyrio martinicus","ss":"porphyrio-martinicus","bnc":"223"},
"348":{"cn":"Sora","sn":"Porzana carolina","ss":"porzana-carolina","bnc":"222"},
"1311":{"cn":"Purple Martin","sn":"Progne subis","ss":"progne-subis","bnc":"383"},
"1577":{"cn":"Prothonotary Warbler","sn":"Protonotaria citrea","ss":"protonotaria-citrea","bnc":"471"},
"151":{"cn":"Herald Petrel","sn":"Pterodroma arminjoniana","ss":"pterodroma-arminjoniana","bnc":"110"},
"154":{"cn":"Bermuda Petrel","sn":"Pterodroma cahow","ss":"pterodroma-cahow","bnc":"109"},
"0":{"cn":"Fea's Petrel","sn":"Pterodroma feae","ss":"pterodroma-feae","bnc":"111"},
"1981":{"cn":"Black-capped Petrel","sn":"Pterodroma hasitata","ss":"pterodroma-hasitata","bnc":"108"},
"171":{"cn":"Great Shearwater","sn":"Puffinus gravis","ss":"puffinus-gravis","bnc":"114"},
"174":{"cn":"Sooty Shearwater","sn":"Puffinus griseus","ss":"puffinus-griseus","bnc":"115"},
"180":{"cn":"Audubon's Shearwater","sn":"Puffinus lherminieri","ss":"puffinus-lherminieri","bnc":"118"},
"177":{"cn":"Manx Shearwater","sn":"Puffinus puffinus","ss":"puffinus-puffinus","bnc":"116"},
"1156":{"cn":"Vermilion Flycatcher","sn":"Pyrocephalus rubinus","ss":"pyrocephalus-rubinus","bnc":"373"},
"1787":{"cn":"Boat-tailed Grackle","sn":"Quiscalus major","ss":"quiscalus-major","bnc":"535"},
"1786":{"cn":"Common Grackle","sn":"Quiscalus quiscula","ss":"quiscalus-quiscula","bnc":"536"},
"341":{"cn":"King Rail","sn":"Rallus elegans","ss":"rallus-elegans","bnc":"220"},
"342":{"cn":"Virginia Rail","sn":"Rallus limicola","ss":"rallus-limicola","bnc":"221"},
"340":{"cn":"Clapper Rail","sn":"Rallus longirostris","ss":"rallus-longirostris","bnc":"219"},
"392":{"cn":"American Avocet","sn":"Recurvirostra americana","ss":"recurvirostra-americana","bnc":"238"},
"1403":{"cn":"Ruby-crowned Kinglet","sn":"Regulus calendula","ss":"regulus-calendula","bnc":"410"},
"1402":{"cn":"Golden-crowned Kinglet","sn":"Regulus satrapa","ss":"regulus-satrapa","bnc":"409"},
"1328":{"cn":"Bank Swallow","sn":"Riparia riparia","ss":"riparia-riparia","bnc":"386"},
"1925":{"cn":"Black-legged Kittiwake","sn":"Rissa tridactyla","ss":"rissa-tridactyla","bnc":"296"},
"1937":{"cn":"Black Skimmer","sn":"Rynchops niger","ss":"rynchops-niger","bnc":"312"},
"1154":{"cn":"Eastern Phoebe","sn":"Sayornis phoebe","ss":"sayornis-phoebe","bnc":"371"},
"456":{"cn":"American Woodcock","sn":"Scolopax minor","ss":"scolopax-minor","bnc":"272"},
"1580":{"cn":"Ovenbird","sn":"Seiurus aurocapilla","ss":"seiurus-aurocapilla","bnc":"474"},
"1582":{"cn":"Louisiana Waterthrush","sn":"Parkesia motacilla","ss":"parkesia-motacilla","bnc":"476"},
"1581":{"cn":"Northern Waterthrush","sn":"Parkesia noveboracensis","ss":"parkesia-noveboracensis","bnc":"475"},
"1576":{"cn":"American Redstart","sn":"Setophaga ruticilla","ss":"setophaga-ruticilla","bnc":"470"},
"1428":{"cn":"Eastern Bluebird","sn":"Sialia sialis","ss":"sialia-sialis","bnc":"413"},
"1347":{"cn":"Red-breasted Nuthatch","sn":"Sitta canadensis","ss":"sitta-canadensis","bnc":"398"},
"1348":{"cn":"White-breasted Nuthatch","sn":"Sitta carolinensis","ss":"sitta-carolinensis","bnc":"399"},
"1350":{"cn":"Brown-headed Nuthatch","sn":"Sitta pusilla","ss":"sitta-pusilla","bnc":"400"},
"60":{"cn":"Common Eider","sn":"Somateria mollissima","ss":"somateria-mollissima","bnc":"179"},
"59":{"cn":"King Eider","sn":"Somateria spectabilis","ss":"somateria-spectabilis","bnc":"180"},
"956":{"cn":"Yellow-bellied Sapsucker","sn":"Sphyrapicus varius","ss":"sphyrapicus-varius","bnc":"356"},
"1770":{"cn":"Dickcissel","sn":"Spiza americana","ss":"spiza-americana","bnc":"496"},
"1704":{"cn":"American Tree Sparrow","sn":"Spizella arborea","ss":"spizella-arborea","bnc":"501"},
"2048":{"cn":"Clay-colored Sparrow","sn":"Spizella pallida","ss":"spizella-pallida","bnc":"503"},
"1705":{"cn":"Chipping Sparrow","sn":"Spizella passerina","ss":"spizella-passerina","bnc":"502"},
"1707":{"cn":"Field Sparrow","sn":"Spizella pusilla","ss":"spizella-pusilla","bnc":"504"},
"1326":{"cn":"Northern Rough-winged Swallow","sn":"Stelgidopteryx serripennis","ss":"stelgidopteryx-serripennis","bnc":"385"},
"512":{"cn":"Long-tailed Jaeger","sn":"Stercorarius longicaudus","ss":"stercorarius-longicaudus","bnc":"278"},
"509":{"cn":"South Polar Skua","sn":"Stercorarius maccormicki","ss":"stercorarius-maccormicki","bnc":"280"},
"511":{"cn":"Parasitic Jaeger","sn":"Stercorarius parasiticus","ss":"stercorarius-parasiticus","bnc":"277"},
"510":{"cn":"Pomarine Jaeger","sn":"Stercorarius pomarinus","ss":"stercorarius-pomarinus","bnc":"276"},
"508":{"cn":"Great Skua","sn":"Stercorarius skua","ss":"stercorarius-skua","bnc":"279"},
"500":{"cn":"Roseate Tern","sn":"Sterna dougallii","ss":"sterna-dougallii","bnc":"302"},
"503":{"cn":"Forster's Tern","sn":"Sterna forsteri","ss":"sterna-forsteri","bnc":"305"},
"501":{"cn":"Common Tern","sn":"Sterna hirundo","ss":"sterna-hirundo","bnc":"303"},
"502":{"cn":"Arctic Tern","sn":"Sterna paradisaea","ss":"sterna-paradisaea","bnc":"304"},
"491":{"cn":"Least Tern","sn":"Sternula antillarum","ss":"sternula-antillarum","bnc":"306"},
"550":{"cn":"Eurasian Collared-Dove","sn":"Streptopelia decaocto","ss":"streptopelia-decaocto","bnc":"323"},
"696":{"cn":"Barred Owl","sn":"Strix varia","ss":"strix-varia","bnc":"338"},
"1779":{"cn":"Eastern Meadowlark","sn":"Sturnella magna","ss":"sturnella-magna","bnc":"530"},
"1780":{"cn":"Western Meadowlark","sn":"Sturnella neglecta","ss":"sturnella-neglecta","bnc":"531"},
"1509":{"cn":"European Starling","sn":"Sturnus vulgaris","ss":"sturnus-vulgaris","bnc":"434"},
"198":{"cn":"Masked Booby","sn":"Sula dactylatra","ss":"sula-dactylatra","bnc":"125"},
"202":{"cn":"Brown Booby","sn":"Sula leucogaster","ss":"sula-leucogaster","bnc":"126"},
"1318":{"cn":"Tree Swallow","sn":"Tachycineta bicolor","ss":"tachycineta-bicolor","bnc":"384"},
"142":{"cn":"Yellow-nosed Albatross","sn":"Thalassarche chlororhynchos","ss":"thalassarche-chlororhynchos","bnc":"106"},
"504":{"cn":"Royal Tern","sn":"Thalasseus maximus","ss":"thalasseus-maximus","bnc":"300"},
"506":{"cn":"Sandwich Tern","sn":"Thalasseus sandvicensis","ss":"thalasseus-sandvicensis","bnc":"301"},
"1382":{"cn":"Bewick's Wren","sn":"Thryomanes bewickii","ss":"thryomanes-bewickii","bnc":"403"},
"1378":{"cn":"Carolina Wren","sn":"Thryothorus ludovicianus","ss":"thryothorus-ludovicianus","bnc":"402"},
"1492":{"cn":"Brown Thrasher","sn":"Toxostoma rufum","ss":"toxostoma-rufum","bnc":"425"},
"402":{"cn":"Spotted Redshank","sn":"Tringa erythropus","ss":"tringa-erythropus","bnc":"241"},
"406":{"cn":"Lesser Yellowlegs","sn":"Tringa flavipes","ss":"tringa-flavipes","bnc":"240"},
"403":{"cn":"Greater Yellowlegs","sn":"Tringa melanoleuca","ss":"tringa-melanoleuca","bnc":"239"},
"405":{"cn":"Willet","sn":"Tringa semipalmata","ss":"tringa-semipalmata","bnc":"243"},
"399":{"cn":"Solitary Sandpiper","sn":"Tringa solitaria","ss":"tringa-solitaria","bnc":"242"},
"1384":{"cn":"House Wren","sn":"Troglodytes aedon","ss":"troglodytes-aedon","bnc":"405"},
"2066":{"cn":"Winter Wren","sn":"Troglodytes hiemalis","ss":"troglodytes-hiemalis","bnc":"406"},
"447":{"cn":"Buff-breasted Sandpiper","sn":"Tryngites subruficollis","ss":"tryngites-subruficollis","bnc":"267"},
"1472":{"cn":"American Robin","sn":"Turdus migratorius","ss":"turdus-migratorius","bnc":"421"},
"1197":{"cn":"Gray Kingbird","sn":"Tyrannus dominicensis","ss":"tyrannus-dominicensis","bnc":"379"},
"1200":{"cn":"Scissor-tailed Flycatcher","sn":"Tyrannus forficatus","ss":"tyrannus-forficatus","bnc":"380"},
"1191":{"cn":"Tropical Kingbird","sn":"Tyrannus melancholicus","ss":"tyrannus-melancholicus","bnc":"376"},
"1201":{"cn":"Fork-tailed Flycatcher","sn":"Tyrannus savana","ss":"tyrannus-savana","bnc":"381"},
"1196":{"cn":"Eastern Kingbird","sn":"Tyrannus tyrannus","ss":"tyrannus-tyrannus","bnc":"378"},
"1195":{"cn":"Western Kingbird","sn":"Tyrannus verticalis","ss":"tyrannus-verticalis","bnc":"377"},
"664":{"cn":"Barn Owl","sn":"Tyto alba","ss":"tyto-alba","bnc":"333"},
"514":{"cn":"Common Murre","sn":"Uria aalge","ss":"uria-aalge","bnc":"12218"},
"515":{"cn":"Thick-billed Murre","sn":"Uria lomvia","ss":"uria-lomvia","bnc":"314"},
"369":{"cn":"Northern Lapwing","sn":"Vanellus vanellus","ss":"vanellus-vanellus","bnc":"228"},
"1536":{"cn":"Orange-crowned Warbler","sn":"Oreothlypis celata","ss":"oreothlypis-celata","bnc":"447"},
"1534":{"cn":"Golden-winged Warbler","sn":"Vermivora chrysoptera","ss":"vermivora-chrysoptera","bnc":"445"},
"1535":{"cn":"Tennessee Warbler","sn":"Oreothlypis peregrina","ss":"oreothlypis-peregrina","bnc":"446"},
"1533":{"cn":"Blue-winged Warbler","sn":"Vermivora cyanoptera","ss":"vermivora-cyanoptera","bnc":"444"},
"1537":{"cn":"Nashville Warbler","sn":"Oreothlypis ruficapilla","ss":"oreothlypis-ruficapilla","bnc":"448"},
"1259":{"cn":"Black-whiskered Vireo","sn":"Vireo altiloquus","ss":"vireo-altiloquus","bnc":"442"},
"1247":{"cn":"Yellow-throated Vireo","sn":"Vireo flavifrons","ss":"vireo-flavifrons","bnc":"438"},
"1254":{"cn":"Warbling Vireo","sn":"Vireo gilvus","ss":"vireo-gilvus","bnc":"439"},
"1233":{"cn":"White-eyed Vireo","sn":"Vireo griseus","ss":"vireo-griseus","bnc":"435"},
"1257":{"cn":"Red-eyed Vireo","sn":"Vireo olivaceus","ss":"vireo-olivaceus","bnc":"441"},
"1256":{"cn":"Philadelphia Vireo","sn":"Vireo philadelphicus","ss":"vireo-philadelphicus","bnc":"440"},
"1250":{"cn":"Blue-headed Vireo","sn":"Vireo solitarius","ss":"vireo-solitarius","bnc":"437"},
"1602":{"cn":"Canada Warbler","sn":"Cardellina canadensis","ss":"cardellina-canadensis","bnc":"483"},
"1600":{"cn":"Hooded Warbler","sn":"Setophaga citrina","ss":"setophaga-citrina","bnc":"481"},
"1601":{"cn":"Wilson's Warbler","sn":"Cardellina pusilla","ss":"cardellina-pusilla","bnc":"482"},
"1781":{"cn":"Yellow-headed Blackbird","sn":"Xanthocephalus xanthocephalus","ss":"xanthocephalus-xanthocephalus","bnc":"532"},
"1988":{"cn":"Sabine's Gull","sn":"Xema sabini","ss":"xema-sabini","bnc":"297"},
"553":{"cn":"White-winged Dove","sn":"Zenaida asiatica","ss":"zenaida-asiatica","bnc":"321"},
"556":{"cn":"Mourning Dove","sn":"Zenaida macroura","ss":"zenaida-macroura","bnc":"322"},
"1726":{"cn":"White-throated Sparrow","sn":"Zonotrichia albicollis","ss":"zonotrichia-albicollis","bnc":"520"},
"1728":{"cn":"White-crowned Sparrow","sn":"Zonotrichia leucophrys","ss":"zonotrichia-leucophrys","bnc":"521"},
"1727":{"cn":"Harris's Sparrow","sn":"Zonotrichia querula","ss":"zonotrichia-querula","bnc":"522"}};